//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapLog
    {
        public int id { get; set; }
        public string keyMap { get; set; }
        public string valueMap { get; set; }
        public string typeMap { get; set; }
        public Nullable<bool> status { get; set; }
        public string Controller { get; set; }
        public Nullable<int> parentId { get; set; }
    }
}
