//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLuong
    {
        public int id { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idLuong { get; set; }
        public Nullable<double> soCongLamTrenThang { get; set; }
        public Nullable<double> soCongNghiKhongPhep { get; set; }
        public Nullable<double> soGioDiTre { get; set; }
        public Nullable<double> soCongNghiCoPhep { get; set; }
        public Nullable<double> soGioOT { get; set; }
        public Nullable<int> trangThai { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public Nullable<int> nguoiTao { get; set; }
        public Nullable<System.DateTime> ngayCapNhat { get; set; }
        public Nullable<int> nguoiCapNhat { get; set; }
        public Nullable<System.DateTime> ngayXoa { get; set; }
        public Nullable<int> nguoiXoa { get; set; }
        public Nullable<bool> xacNhanXoa { get; set; }
    
        public virtual Luong Luong { get; set; }
        public virtual User User { get; set; }
    }
}
