//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuthorization
    {
        public int Id { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idMenu { get; set; }
        public Nullable<bool> permissionGet { get; set; }
        public Nullable<bool> permissionPost { get; set; }
        public Nullable<bool> permissionPut { get; set; }
        public Nullable<bool> permissionDelete { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public Nullable<int> nguoiTao { get; set; }
        public Nullable<System.DateTime> ngayCapNhat { get; set; }
        public Nullable<int> nguoiCapNhat { get; set; }
        public Nullable<System.DateTime> ngayXoa { get; set; }
        public Nullable<int> nguoiXoa { get; set; }
        public Nullable<bool> xacNhanXoa { get; set; }
        public Nullable<bool> hieuLuc { get; set; }
        public Nullable<int> idPage { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Page Page { get; set; }
        public virtual User User { get; set; }
    }
}
