//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.LogHistorys = new HashSet<LogHistory>();
            this.UserAuthorizations = new HashSet<UserAuthorization>();
            this.UserLuongs = new HashSet<UserLuong>();
            this.BaiViets = new HashSet<BaiViet>();
        }
    
        public int Id { get; set; }
        public string tenTaiKhoan { get; set; }
        public string matKhau { get; set; }
        public string hoVaTen { get; set; }
        public string soDienThoai { get; set; }
        public string email { get; set; }
        public string dcThuongTru { get; set; }
        public string dcTamTru { get; set; }
        public Nullable<System.DateTime> thoiGianLamViec { get; set; }
        public string soTaiKhoan { get; set; }
        public string codeNganHang { get; set; }
        public string anhDaiDien { get; set; }
        public Nullable<bool> dangThuViec { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public Nullable<int> nguoiTao { get; set; }
        public Nullable<System.DateTime> ngayCapNhat { get; set; }
        public Nullable<int> nguoiCapNhat { get; set; }
        public Nullable<System.DateTime> ngayXoa { get; set; }
        public Nullable<int> nguoiXoa { get; set; }
        public Nullable<bool> xacNhanXoa { get; set; }
        public Nullable<bool> hieuLuc { get; set; }
        public Nullable<int> capDoTaiKhoan { get; set; }
        public string chuKyUser { get; set; }
        public string nguyenQuan { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public Nullable<bool> gioiTinh { get; set; }
        public string mstCaNhan { get; set; }
        public string danToc { get; set; }
        public string tringDoVanHoa { get; set; }
        public string soDienThoaiKhac { get; set; }
        public string zalo { get; set; }
        public string soCCCD { get; set; }
        public string anhCCCDMatTruoc { get; set; }
        public string anhCCCDMatSau { get; set; }
        public string tenTaiKhoanNganHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogHistory> LogHistorys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAuthorization> UserAuthorizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLuong> UserLuongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiViet> BaiViets { get; set; }
    }
}
