//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.Kho_QLK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donvinhap_QLK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donvinhap_QLK()
        {
            this.phieuNhap_QLK = new HashSet<phieuNhap_QLK>();
        }
    
        public string MaDVN_QLK { get; set; }
        public string TenDVN_QLK { get; set; }
        public string Diachi_QLK { get; set; }
        public string Sdt_QLK { get; set; }
        public Nullable<bool> Hieuluc_QLK { get; set; }
        public string Mail_QLK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phieuNhap_QLK> phieuNhap_QLK { get; set; }
    }
}
