//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.Kho_QLK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giamgia_QLK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Giamgia_QLK()
        {
            this.Sanphamgiamgia_QLK = new HashSet<Sanphamgiamgia_QLK>();
        }
    
        public int Id { get; set; }
        public string Tenchuongtrinh_QLK { get; set; }
        public Nullable<System.DateTime> Ngaytao_QLK { get; set; }
        public string Nguoitao_QLK { get; set; }
        public Nullable<System.DateTime> Ngayapdung_QLK { get; set; }
        public Nullable<System.DateTime> Ngayketthuc_QLK { get; set; }
        public string Thele_QLK { get; set; }
        public Nullable<int> Noidung_QLK { get; set; }
        public Nullable<bool> Hieuluc_QLK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sanphamgiamgia_QLK> Sanphamgiamgia_QLK { get; set; }
    }
}
