//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.Kho_QLK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kekho_QLK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kekho_QLK()
        {
            this.Tangkekho_QLK = new HashSet<Tangkekho_QLK>();
        }
    
        public string Make_QLK { get; set; }
        public string Makho_QLK { get; set; }
        public Nullable<bool> Hieuluc { get; set; }
    
        public virtual kho_QLK kho_QLK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tangkekho_QLK> Tangkekho_QLK { get; set; }
    }
}
