//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.Kho_QLK
{
    using System;
    using System.Collections.Generic;
    
    public partial class loaisp_QLK
    {
        public string Maloai_QLK { get; set; }
        public string Tenloai_QLK { get; set; }
        public Nullable<bool> Hieuluc_QLK { get; set; }
    }
}
