//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.Kho_QLK
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieuNhap_QLK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phieuNhap_QLK()
        {
            this.ct_phieuNhap_QLK = new HashSet<ct_phieuNhap_QLK>();
        }
    
        public string Maphieunhap_QLK { get; set; }
        public string Makho_QLK { get; set; }
        public string Madonvinhap_QLK { get; set; }
        public Nullable<int> Tongtiennhap_QLK { get; set; }
        public string Nguoilapphieu_QLK { get; set; }
        public Nullable<System.DateTime> Ngaylapphieu_QLK { get; set; }
        public Nullable<System.DateTime> Ngaychinhsua_QLK { get; set; }
        public string Nguoichinhsua_QLK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ct_phieuNhap_QLK> ct_phieuNhap_QLK { get; set; }
        public virtual Donvinhap_QLK Donvinhap_QLK { get; set; }
    }
}
