//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.Kho_QLK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYKHOEntities : DbContext
    {
        public QUANLYKHOEntities()
            : base("name=QUANLYKHOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ct_phieuNhap_QLK> ct_phieuNhap_QLK { get; set; }
        public virtual DbSet<Donvinhap_QLK> Donvinhap_QLK { get; set; }
        public virtual DbSet<Giamgia_QLK> Giamgia_QLK { get; set; }
        public virtual DbSet<Kekho_QLK> Kekho_QLK { get; set; }
        public virtual DbSet<kho_QLK> kho_QLK { get; set; }
        public virtual DbSet<loaisp_QLK> loaisp_QLK { get; set; }
        public virtual DbSet<phieuNhap_QLK> phieuNhap_QLK { get; set; }
        public virtual DbSet<sanpham_QLK> sanpham_QLK { get; set; }
        public virtual DbSet<Sanphamgiamgia_QLK> Sanphamgiamgia_QLK { get; set; }
        public virtual DbSet<Tangkekho_QLK> Tangkekho_QLK { get; set; }
        public virtual DbSet<Hangtang_QLK> Hangtang_QLK { get; set; }
    }
}
