//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.Kho_QLK
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham_QLK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanpham_QLK()
        {
            this.Hangtang_QLK = new HashSet<Hangtang_QLK>();
            this.Sanphamgiamgia_QLK = new HashSet<Sanphamgiamgia_QLK>();
        }
    
        public string Masp_QLK { get; set; }
        public string Tensp_QLK { get; set; }
        public string Hinhanh_QLK { get; set; }
        public string Loaisp_QLK { get; set; }
        public Nullable<int> Giaban_QLK { get; set; }
        public Nullable<bool> Hieuluc_QLK { get; set; }
        public Nullable<System.DateTime> Ngaynhap_QLK { get; set; }
        public string Nguoinhap_QLK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hangtang_QLK> Hangtang_QLK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sanphamgiamgia_QLK> Sanphamgiamgia_QLK { get; set; }
    }
}
