//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.Kho_QLK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tangkekho_QLK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tangkekho_QLK()
        {
            this.Hangtang_QLK = new HashSet<Hangtang_QLK>();
        }
    
        public string Matang_QLK { get; set; }
        public string Make_QLK { get; set; }
        public string Makho_QLK { get; set; }
        public Nullable<bool> Hieuluc { get; set; }
    
        public virtual Kekho_QLK Kekho_QLK { get; set; }
        public virtual kho_QLK kho_QLK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hangtang_QLK> Hangtang_QLK { get; set; }
    }
}
